### ISSUE TITLE
Rlang is not installing

### ISSUE THREAD

**Issue by mgolderg** [r-lib/rlang#1433] opened 2022-06-28 18:57 UTC
June 28, 2022. Rlang is not installing. 

RStudio 2022.02.3 Build 492 (Mac OS)

> version
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          1.3                         
year           2022                        
month          03                          
day            10                          
svn rev        81868                       
language       R                           
version.string R version 4.1.3 (2022-03-10)
nickname       One Push-Up  
   
> install.packages("rlang")

  There is a binary version available but the source version is later:
      binary source needs_compilation
rlang  1.0.2  1.0.3              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) y
installing the source package ‘rlang’

trying URL 'https://cran.rstudio.com/src/contrib/rlang_1.0.3.tar.gz'
Content type 'application/x-gzip' length 740744 bytes (723 KB)
==================================================
downloaded 723 KB

* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘rlang’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/rlang’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/rlang’
Warning in install.packages :
  installation of package ‘rlang’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/g4/jw0bjcks1gs6_lnbxqnqk2hm0000gn/T/Rtmpi4du8G/downloaded_packages’
>

**Comment by DWJ27** [comment] 2022-06-29 01:01
I'm faced with a similar issue when trying to install "pkgload".
When I run install.packages("pkgload") the following error pops up.

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'rlang' 1.0.2 is being loaded, but >= 1.0.3 is required

I then try to install the latest version of "rlang", but get the same error as you've listed above.

**Comment by lionel-** [comment] 2022-06-29 07:44
Duplicate of #1431 (cc @DWJ27).

You could fix your build environment. The first google hit suggests you need to install XCode tools: https://ma.ttias.be/mac-os-xcrun-error-invalid-active-developer-path-missing-xcrun/

As a temporary fix, you could install an older version of pkgload that doesn't require the latest rlang.

Or you could wait for the binaries to be published (this usually takes a few days).

**Closed** 2022-08-19 12:58 UTC
Labels: install issue :fire: :fire: :fire:
