### ISSUE TITLE
! Column `minute` (size 1) must match the data frame (size 338).

### ISSUE THREAD

**Issue by hgftitanium** [r-lib/rlang#1392] opened 2022-04-19 19:15 UTC
ℹ In file slice.c at line 188.
ℹ This is an internal error in the rlang package, please report it to the package authors.
Backtrace:
    ▆
 1. ├─global main()
 2. │ ├─out_data[-elim, ]
 3. │ └─tibble:::`[.tbl_df`(out_data, -elim, )
 4. │   └─tibble:::tbl_subset_row(xo, i = i, i_arg)
 5. │     └─base::lapply(unclass(x), vec_slice, i = i)
 6. │       └─vctrs FUN(X[[i]], ...)
 7. └─rlang:::stop_internal_c_lib(...)
 8.   └─rlang::abort(message, call = call, .internal = TRUE)

**Comment by lionel-** [comment] 2022-04-20 06:54
Hello, without a reprex so we can reproduce locally we won't be able to fix this.

**Comment by lionel-** [comment] 2022-05-25 07:58
Thanks for the report but in the future, please supply a reproducible example. It takes work to reduce an error to a minimal example, but unfortunately without one we can't figure out what the problem is. I'm closing this now but feel free to reply with a reprex.

**Closed by lionel-** 2022-05-25 07:58 UTC
