### ISSUE TITLE
"Trace data is not square" error with pipes and `last_error()`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rlang#938] opened 2020-03-06 19:54 UTC
I have seen this error in a number of places (often in testthat), but cannot come up with a simpler example that doesn't use dplyr. Thanks to @juliasilge for this example

Using cran dplyr, magrittr, and rlang.

I get a different error with reprex, so pasting this here manually:

```r
> library(rlang)
> library(dplyr, warn.conflicts = FALSE)
> 
> mtcars %>%
+   select(mgp)
Error: Can't subset columns that don't exist.
x The column `mgp` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.
> 
> last_error()
Error: Internal error: Trace data is not square.
Run `rlang::last_error()` to see where the error occurred.
```

The actual code:

```r
library(rlang)
library(dplyr, warn.conflicts = FALSE)

mtcars %>%
  select(mgp)

last_error()
```

From a little digging, this error comes from here:
https://github.com/r-lib/rlang/blob/d780f160c817da5034e8652769935c3949eff06b/R/trace.R#L662

One thing of note, `n_collapsed` is returning `NULL` here
https://github.com/r-lib/rlang/blob/d780f160c817da5034e8652769935c3949eff06b/R/trace.R#L647

So your note at the top of `branch_uncollapse_pipe()` that says "Assumes a backtrace branch with collapsed pipe" might not hold in this case for some reason?

**Comment by batpigandme** [comment] 2020-03-18 14:45
I don't think there are any pipes in this one, but it is triggering `Error: Internal error: Trace data is not square.` when I run it **interactively**.
```r
library(tidyverse)
library(lubridate)
test <- tibble(A=1:5, B=hours(1:5))
test
nested <- test %>% nest(B2=B)
nested
unnested <- nested %>% unnest(cols=B2)
# this triggers
# Error: No common type for `..1$B2$B` <Period> and `..2$B2$B` <Period>.
# Run `rlang::last_error()` to see where the error occurred.
rlang::last_error()
# Error: Internal error: Trace data is not square.
# Run `rlang::last_error()` to see where the error occurred.
```
If I do the same sequence of steps, I get a backtrace in my **reprex**:
``` r
library(tidyverse)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
test <- tibble(A=1:5, B=hours(1:5))
test
#> # A tibble: 5 x 2
#>       A B       
#>   <int> <Period>
#> 1     1 1H 0M 0S
#> 2     2 2H 0M 0S
#> 3     3 3H 0M 0S
#> 4     4 4H 0M 0S
#> 5     5 5H 0M 0S
nested <- test %>% nest(B2=B)
nested
#> # A tibble: 5 x 2
#>       A B2              
#>   <int> <list>          
#> 1     1 <tibble [1 × 1]>
#> 2     2 <tibble [1 × 1]>
#> 3     3 <tibble [1 × 1]>
#> 4     4 <tibble [1 × 1]>
#> 5     5 <tibble [1 × 1]>
unnested <- nested %>% unnest(cols=B2)
#> Error: No common type for `..1$B2$B` <Period> and `..2$B2$B` <Period>.
#> Backtrace:
#>      █
#>   1. ├─nested %>% unnest(cols = B2)
#>   2. │ ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
#>   3. │ └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
#>   4. │   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
#>   5. │     └─`_fseq`(`_lhs`)
#>   6. │       └─magrittr::freduce(value, `_function_list`)
#>   7. │         ├─base::withVisible(function_list[[k]](value))
#>   8. │         └─function_list[[k]](value)
#>   9. │           ├─tidyr::unnest(., cols = B2)
#>  10. │           └─tidyr:::unnest.data.frame(., cols = B2)
#>  11. │             └─tidyr::unchop(data, !!cols, keep_empty = keep_empty, ptype = ptype)
#>  12. │               └─vctrs::vec_rbind(!!!x, .ptype = ptype)
#>  13. ├─vctrs:::vec_ptype2_dispatch_s3(x = x, y = y, x_arg = x_arg, y_arg = y_arg)
#>  14. └─vctrs:::vec_ptype2.default(x = x, y = y, x_arg = x_arg, y_arg = y_arg)
#>  15.   └─vctrs::stop_incompatible_type(x, y, x_arg = x_arg, y_arg = y_arg)
#>  16.     └─vctrs:::stop_incompatible(...)
#>  17.       └─vctrs:::stop_vctrs(...)
```

<sup>Created on 2020-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by beanumber** [comment] 2020-03-31 20:34
I think I have another wild caught example:

https://win-builder.r-project.org/incoming_pretest/macleish_0.3.5_20200327_174156/Debian/00check.log

Of course, it works for me locally just fine. The test that is failing is:

```{r}
  macleish_layers %>%
    purrr::map(sf::st_crs) %>%
    purrr::map_int(`$`, epsg) %>%
    `==`(4326) %>%
    all() %>%
    expect_true()
```
I know the syntax looks weird, but it works (on some platforms).

**Comment by leungi** [comment] 2020-05-04 23:48
Similar issue when using `sf::st_as_sf()`

```r
> dat <- structure(list(name = "mvp", latitude = 12.2677616666667,
+     longitude = -100.753396388889, value = 7055), class = c("tbl_df",
+ "tbl", "data.frame"), row.names = c(NA, -1L))
>
> sf::st_as_sf(dat, coords=c("longitude", "latitude"))
Error: `x` must be a vector, not a `sfc_POINT/sfc` object.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
Error: Internal error: Trace data is not square.
```

#### Workaround
```r
> sf::st_as_sf(as.data.frame(dat), coords=c("longitude", "latitude"))
Simple feature collection with 1 feature and 2 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: -100.7534 ymin: 12.26776 xmax: -100.7534 ymax: 12.26776
epsg (SRID):    NA
proj4string:    NA
  name value                   geometry
1  mvp  7055 POINT (-100.7534 12.26776)
```

#### Session
```r
> sessioninfo::session_info()
â Session info âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
 setting  value
 version  R version 3.6.0 (2019-04-26)
 os       Red Hat Enterprise Linux Server 7.3 (Maipo)
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Chicago
 date     2020-05-04

â Packages âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
 package       * version    date       lib source
 assertthat      0.2.1      2019-03-21 [1] CRAN (R 3.5.2)
 backports       1.1.4      2019-04-10 [1] CRAN (R 3.5.2)
 class           7.3-15     2019-01-01 [1] CRAN (R 3.6.0)
 classInt        0.4-3      2020-04-07 [1] CRAN (R 3.6.0)
 cli             2.0.2      2020-02-28 [1] CRAN (R 3.6.0)
 crayon          1.3.4      2017-09-16 [1] CRAN (R 3.5.2)
 DBI             1.0.0      2018-05-02 [1] CRAN (R 3.5.2)
 dplyr         * 0.8.5      2020-03-07 [1] CRAN (R 3.6.0)
 e1071           1.7-1      2019-03-19 [1] CRAN (R 3.5.2)
 ellipsis        0.3.0      2019-09-20 [1] CRAN (R 3.6.0)
 fansi           0.4.0      2018-10-05 [1] CRAN (R 3.5.2)
 glue            1.4.0      2020-04-03 [1] CRAN (R 3.6.0)
 here            0.1        2017-05-28 [1] CRAN (R 3.5.2)
 kapow           0.0.0.9000 2020-03-24 [1] local
 KernSmooth      2.23-16    2019-10-15 [1] CRAN (R 3.6.0)
 lifecycle       0.2.0      2020-03-06 [1] CRAN (R 3.6.0)
 magrittr        1.5        2014-11-22 [1] CRAN (R 3.5.2)
 pillar          1.4.3      2019-12-20 [1] CRAN (R 3.6.0)
 pkgconfig       2.0.2      2018-08-16 [1] CRAN (R 3.5.2)
 purrr           0.3.3      2019-10-18 [1] CRAN (R 3.6.0)
 qs              0.19.1     2019-10-04 [1] CRAN (R 3.6.0)
 R6              2.4.0      2019-02-14 [1] CRAN (R 3.5.2)
 RApiSerialize   0.1.0      2014-04-19 [1] CRAN (R 3.5.2)
 Rcpp            1.0.1      2019-03-17 [1] CRAN (R 3.5.2)
 rlang           0.4.6      2020-05-02 [1] CRAN (R 3.6.0)
 rprojroot       1.3-2      2018-01-03 [1] CRAN (R 3.5.2)
 sessioninfo     1.1.1      2018-11-05 [1] CRAN (R 3.5.2)
 sf            * 0.7-4      2019-04-25 [1] CRAN (R 3.5.2)
 tibble          3.0.0      2020-03-30 [1] CRAN (R 3.6.0)
 tidyselect      1.0.0      2020-01-27 [1] CRAN (R 3.6.0)
 units           0.6-3      2019-05-03 [1] CRAN (R 3.5.2)
 vctrs           0.2.4      2020-03-10 [1] CRAN (R 3.6.0)
 withr           2.1.2      2018-03-15 [1] CRAN (R 3.5.2)

[1] /usr/lib64/R/library
[2] /usr/share/R/library
```

**Comment by lionel-** [comment] 2020-05-05 05:57
Sorry about this, I'll look into it once everything is ready for dplyr 1.0.

**Comment by lionel-** [comment] 2020-05-13 13:14
Finally fixed in the dev version.

**Comment by leungi** [comment] 2020-05-26 06:01
> Similar issue when using `sf::st_as_sf()`
> 
> ```r
> > dat <- structure(list(name = "mvp", latitude = 12.2677616666667,
> +     longitude = -100.753396388889, value = 7055), class = c("tbl_df",
> + "tbl", "data.frame"), row.names = c(NA, -1L))
> >
> > sf::st_as_sf(dat, coords=c("longitude", "latitude"))
> Error: `x` must be a vector, not a `sfc_POINT/sfc` object.
> Run `rlang::last_error()` to see where the error occurred.
> > rlang::last_error()
> Error: Internal error: Trace data is not square.
> ```
> 
> #### Workaround
> ```r
> > sf::st_as_sf(as.data.frame(dat), coords=c("longitude", "latitude"))
> Simple feature collection with 1 feature and 2 fields
> geometry type:  POINT
> dimension:      XY
> bbox:           xmin: -100.7534 ymin: 12.26776 xmax: -100.7534 ymax: 12.26776
> epsg (SRID):    NA
> proj4string:    NA
>   name value                   geometry
> 1  mvp  7055 POINT (-100.7534 12.26776)
> ```
> 
> #### Session
> ```r
> > sessioninfo::session_info()
> â Session info âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
>  setting  value
>  version  R version 3.6.0 (2019-04-26)
>  os       Red Hat Enterprise Linux Server 7.3 (Maipo)
>  system   x86_64, linux-gnu
>  ui       X11
>  language (EN)
>  collate  en_US.UTF-8
>  ctype    en_US.UTF-8
>  tz       America/Chicago
>  date     2020-05-04
> 
> â Packages âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
>  package       * version    date       lib source
>  assertthat      0.2.1      2019-03-21 [1] CRAN (R 3.5.2)
>  backports       1.1.4      2019-04-10 [1] CRAN (R 3.5.2)
>  class           7.3-15     2019-01-01 [1] CRAN (R 3.6.0)
>  classInt        0.4-3      2020-04-07 [1] CRAN (R 3.6.0)
>  cli             2.0.2      2020-02-28 [1] CRAN (R 3.6.0)
>  crayon          1.3.4      2017-09-16 [1] CRAN (R 3.5.2)
>  DBI             1.0.0      2018-05-02 [1] CRAN (R 3.5.2)
>  dplyr         * 0.8.5      2020-03-07 [1] CRAN (R 3.6.0)
>  e1071           1.7-1      2019-03-19 [1] CRAN (R 3.5.2)
>  ellipsis        0.3.0      2019-09-20 [1] CRAN (R 3.6.0)
>  fansi           0.4.0      2018-10-05 [1] CRAN (R 3.5.2)
>  glue            1.4.0      2020-04-03 [1] CRAN (R 3.6.0)
>  here            0.1        2017-05-28 [1] CRAN (R 3.5.2)
>  kapow           0.0.0.9000 2020-03-24 [1] local
>  KernSmooth      2.23-16    2019-10-15 [1] CRAN (R 3.6.0)
>  lifecycle       0.2.0      2020-03-06 [1] CRAN (R 3.6.0)
>  magrittr        1.5        2014-11-22 [1] CRAN (R 3.5.2)
>  pillar          1.4.3      2019-12-20 [1] CRAN (R 3.6.0)
>  pkgconfig       2.0.2      2018-08-16 [1] CRAN (R 3.5.2)
>  purrr           0.3.3      2019-10-18 [1] CRAN (R 3.6.0)
>  qs              0.19.1     2019-10-04 [1] CRAN (R 3.6.0)
>  R6              2.4.0      2019-02-14 [1] CRAN (R 3.5.2)
>  RApiSerialize   0.1.0      2014-04-19 [1] CRAN (R 3.5.2)
>  Rcpp            1.0.1      2019-03-17 [1] CRAN (R 3.5.2)
>  rlang           0.4.6      2020-05-02 [1] CRAN (R 3.6.0)
>  rprojroot       1.3-2      2018-01-03 [1] CRAN (R 3.5.2)
>  sessioninfo     1.1.1      2018-11-05 [1] CRAN (R 3.5.2)
>  sf            * 0.7-4      2019-04-25 [1] CRAN (R 3.5.2)
>  tibble          3.0.0      2020-03-30 [1] CRAN (R 3.6.0)
>  tidyselect      1.0.0      2020-01-27 [1] CRAN (R 3.6.0)
>  units           0.6-3      2019-05-03 [1] CRAN (R 3.5.2)
>  vctrs           0.2.4      2020-03-10 [1] CRAN (R 3.6.0)
>  withr           2.1.2      2018-03-15 [1] CRAN (R 3.5.2)
> 
> [1] /usr/lib64/R/library
> [2] /usr/share/R/library
> ```

Confirmed latest fix resolves my issue; hope it does for others too 👌🙏

**Comment by MyKo101** [comment] 2020-06-09 19:32
To contribute, I was also having this error when running `devtools::check()` on my package. 

My solution was to load all required packages in the `testthat.R` file and get rid of all `::` references in my test code.

My package uses quite a few functions that create/manipulate environments and frequently uses pipes so that may be related to this issue somehow, but can't be certain without breaking my entire code.

**Comment by lionel-** [comment] 2020-06-10 05:43
The workaround is to install dev rlang. The bug only appears in case something is wrong, so it won't affect CRAN checks (unless something else is wrong). I'll send a fix to CRAN this week.

**Closed** 2020-06-15 10:16 UTC
Labels: bug
