### ISSUE TITLE
Error in arrange_impl(.data, dots) :    Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0

### ISSUE THREAD

**Issue by subratiter1** [r-lib/rlang#748] opened 2019-03-26 03:57 UTC
Error in arrange_impl(.data, dots) : 
  Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.

**Comment by lionel-** [comment] 2019-03-26 07:46
You likely had an installation problem when upgrading dplyr. Please reinstall dplyr in a fresh session.

Duplicate of https://github.com/r-lib/rlang/issues/674

**Closed by lionel-** 2019-03-26 07:46 UTC
