### ISSUE TITLE
printing argument of a function changes the result of enquo

### ISSUE THREAD

**Issue by danilinares** [r-lib/rlang#837] opened 2019-09-30 09:14 UTC
I found that printing the argument of a function changes the result of enquo

example_function <- function(x) x^2

my_function <- function(fun) {
  quo_name(enquo(fun))
}
my_function(example_function)

my_function <- function(fun) {
  print(is.function(fun))
  quo_name(enquo(fun))
}
my_function(example_function)

**Comment by lionel-** [comment] 2019-09-30 09:21
This is expected behaviour, once a promise is forced it can't be `enquo()`. This should be documented somewhere.

**Comment by lionel-** [comment] 2021-03-29 10:50
Duplicate of #884.

**Closed by lionel-** 2021-03-29 10:50 UTC
Labels: doc :ledger:, tidyeval
