### ISSUE TITLE
env_unbind and env_set should return previous values

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#178] opened 2017-06-15 18:49 UTC
Associated with that binding, invisibly.

**Comment by lionel-** [comment] 2017-06-15 18:50
shouldn't they return the input environment?

**Comment by hadley** [comment] 2017-06-15 18:51
In this case, I think returning the previous values would be more useful.

**Comment by lionel-** [comment] 2018-03-05 14:17
Duplicate of 426

**Closed by lionel-** 2018-03-05 14:17 UTC
Labels: env
