### ISSUE TITLE
Please consider adding default argument to `env_get`

### ISSUE THREAD

**Issue by vspinu** [r-lib/rlang#373] opened 2018-01-19 21:07 UTC
Base R is annoying because you always need `if (exists(...)) get(...)`. It's a common practice in modern languages to have default arguments when extraction fails.

Incidentally `get_env` does have the `default` :)

**Comment by lionel-** [comment] 2018-03-05 14:15
Duplicate of #179

**Closed by lionel-** 2018-03-05 14:15 UTC
Labels: env
