### ISSUE TITLE
Ensure all dots are named/unnamed in `dots_list()`

### ISSUE THREAD

**Issue by rvomm** [r-lib/rlang#1245] opened 2021-07-29 10:19 UTC
It would be nice to have an option to ensure that all dots are named (or unnamed). Currently `dots_list()` only has an auto-naming option with `.named = TRUE`. To ensure all dots are named, a small workaround like this is required: 

```
library(rlang)
dots_list_named <- function(...){
  dots <- dots_list(..., .named = FALSE)
  if(! is_named(dots))
    abort("")
  dots
}
dots_list(x = 1, 2)
dots_list_named(x = 1, 2)
```

Ideally, this would be included in the `.named` argument, but this changes the function's current behavior.
```
.named = c("default", "build", "all", "none")
``` 
More practical would be to include an `.ensure_named` argument taking values, but this might conflict with the `.named = TRUE` behavior.
```
.ensure_named = c("false", "named",  "unnamed")
```

**Comment by lionel-** [comment] 2021-08-23 08:32
IIUC this is a duplicate of #1236.

**Closed by lionel-** 2021-08-23 08:32 UTC
